files:
  - source: /app/src/lang/translations/en-US.yaml
    translation: /app/src/lang/translations/%locale%.yaml

pull_request_labels:
  - ':cake: Chore'
  - ':elevator: Web'
  - ':file_folder: Studio Misc.'
  - ':fire:'
